package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"errors"
	"fmt"
	"strconv"

	"github.com/ne241099/daifugo-server/graph/model"
	"github.com/ne241099/daifugo-server/internal/auth"
	"github.com/ne241099/daifugo-server/internal/game"
)

// ID is the resolver for the id field.
func (r *cardResolver) ID(ctx context.Context, obj *game.Card) (int32, error) {
	return int32(obj.ID), nil
}

// Suit is the resolver for the suit field.
func (r *cardResolver) Suit(ctx context.Context, obj *game.Card) (string, error) {
	return obj.Suit.String(), nil
}

// Rank is the resolver for the rank field.
func (r *cardResolver) Rank(ctx context.Context, obj *game.Card) (int32, error) {
	return int32(obj.Rank), nil
}

// Turn is the resolver for the turn field.
func (r *gameResolver) Turn(ctx context.Context, obj *game.Game) (int32, error) {
	return int32(obj.Turn), nil
}

// Players is the resolver for the players field.
func (r *gameResolver) Players(ctx context.Context, obj *game.Game) ([]*game.Player, error) {
	currentUserID, err := auth.GetUserID(ctx)
	if err != nil {
		return nil, fmt.Errorf("unauthorized: %w", err)
	}

	// 自分がプレイヤーに含まれているか確認
	isSpectator := true
	for _, p := range obj.Players {
		if p.UserID == currentUserID {
			isSpectator = false
			break
		}
	}

	// プレイヤーごとの手札をフィルタリングして返す
	result := make([]*game.Player, len(obj.Players))

	for i, p := range obj.Players {
		// 構造体のコピーを作成
		pCopy := *p

		// 表示条件:
		// ゲームが終了している
		// 自分が観戦者である
		// 自分の手札である
		isVisible := obj.IsFinished || isSpectator || (p.UserID == currentUserID)

		if !isVisible {
			// 条件を満たさない場合、手札を空にする
			pCopy.Hand = []*game.Card{}
		}

		result[i] = &pCopy
	}

	return result, nil
}

// PassCount is the resolver for the passCount field.
func (r *gameResolver) PassCount(ctx context.Context, obj *game.Game) (int32, error) {
	return int32(obj.PassCount), nil
}

// User is the resolver for the user field.
func (r *gamePlayerResolver) User(ctx context.Context, obj *game.Player) (*model.User, error) {
	u, err := r.GetUserUseCase.Execute(ctx, obj.UserID)
	if err != nil {
		return nil, err
	}

	return &model.User{
		ID:        strconv.FormatInt(u.ID, 10),
		Name:      u.Name,
		Email:     u.Email,
		CreatedAt: u.CreatedAt,
		UpdatedAt: u.UpdatedAt,
	}, nil
}

// Rank is the resolver for the rank field.
func (r *gamePlayerResolver) Rank(ctx context.Context, obj *game.Player) (int32, error) {
	return int32(obj.Rank), nil
}

// SignUp is the resolver for the signUp field.
func (r *mutationResolver) SignUp(ctx context.Context, in model.SignUpInput) (*model.User, error) {
	u, err := r.SignUpUseCase.Execute(ctx, in)
	if err != nil {
		return nil, errors.Join(err)
	}
	return &model.User{
		ID:        strconv.FormatInt(u.ID, 10),
		Email:     u.Email,
		Name:      u.Name,
		CreatedAt: u.CreatedAt,
		UpdatedAt: u.CreatedAt,
	}, nil
}

// CreateRoom is the resolver for the createRoom field.
// 部屋を作成する
func (r *mutationResolver) CreateRoom(ctx context.Context, name string) (*model.Room, error) {
	ownerID, err := auth.GetUserID(ctx)
	if err != nil {
		return nil, fmt.Errorf("unauthorized: %w", err)
	}

	// UseCaseを実行
	createdRoom, err := r.CreateRoomUseCase.Execute(ctx, name, ownerID)
	if err != nil {
		return nil, err
	}

	// ドメインモデル から GraphQLモデル への変換
	gqlRoom := mapRoomToGraphQL(createdRoom)

	r.Hub.Publish("room_created", gqlRoom, nil)
	return gqlRoom, nil
}

// JoinRoom is the resolver for the joinRoom field.
// 部屋に参加する
func (r *mutationResolver) JoinRoom(ctx context.Context, roomID string) (*model.Room, error) {
	rID, err := strconv.ParseInt(roomID, 10, 64)
	if err != nil {
		return nil, errors.Join(err)
	}

	userID, err := auth.GetUserID(ctx)
	if err != nil {
		return nil, fmt.Errorf("unauthorized: %w", err)
	}
	joinedRoom, err := r.JoinRoomUseCase.Execute(ctx, rID, userID)
	if err != nil {
		return nil, err
	}

	memberIDsStr := make([]string, len(joinedRoom.MemberIDs))
	for i, mid := range joinedRoom.MemberIDs {
		memberIDsStr[i] = strconv.FormatInt(mid, 10)
	}

	gqlRoom := mapRoomToGraphQL(joinedRoom)

	r.Hub.Publish("room_updated", gqlRoom, nil)
	return gqlRoom, nil
}

// StartGame is the resolver for the startGame field.
func (r *mutationResolver) StartGame(ctx context.Context, roomID string) (*model.Room, error) {
	rid, _ := strconv.ParseInt(roomID, 10, 64)

	// UseCaseを実行
	room, err := r.StartGameUseCase.Execute(ctx, rid)
	if err != nil {
		return nil, err
	}

	if r.Hub != nil {
		r.Hub.Publish(roomID, "game_started", nil)
	}

	return mapRoomToGraphQL(room), nil
}

// PlayCard is the resolver for the playCard field.
func (r *mutationResolver) PlayCard(ctx context.Context, roomID string, cardIDs []int32) (*model.Room, error) {
	rid, _ := strconv.ParseInt(roomID, 10, 64)

	// 実行ユーザーを取得
	userID, err := auth.GetUserID(ctx)
	if err != nil {
		return nil, fmt.Errorf("unauthorized: %w", err)
	}

	targetCardIDs := make([]int, len(cardIDs))
	for i, id := range cardIDs {
		targetCardIDs[i] = int(id)
	}

	// UseCaseを実行
	room, err := r.PlayCardUseCase.Execute(ctx, rid, userID, targetCardIDs)
	if err != nil {
		return nil, err
	}

	if r.Hub != nil {
		r.Hub.Publish(roomID, "game_update", nil)
	}

	return mapRoomToGraphQL(room), nil
}

// Pass is the resolver for the pass field.
func (r *mutationResolver) Pass(ctx context.Context, roomID string) (*model.Room, error) {
	rid, _ := strconv.ParseInt(roomID, 10, 64)

	// 実行ユーザーを取得
	userID, err := auth.GetUserID(ctx)
	if err != nil {
		return nil, fmt.Errorf("unauthorized: %w", err)
	}

	// UseCaseを実行
	room, err := r.PassUseCase.Execute(ctx, rid, userID)
	if err != nil {
		return nil, err
	}

	if r.Hub != nil {
		r.Hub.Publish(roomID, "game_update", nil)
	}

	return mapRoomToGraphQL(room), nil
}

// LeaveRoom is the resolver for the leaveRoom field.
func (r *mutationResolver) LeaveRoom(ctx context.Context, roomID string) (bool, error) {
	rid, _ := strconv.ParseInt(roomID, 10, 64)

	// 実行ユーザーを取得
	userID, err := auth.GetUserID(ctx)
	if err != nil {
		return false, fmt.Errorf("unauthorized: %w", err)
	}

	// UseCaseを実行
	if err := r.LeaveRoomUseCase.Execute(ctx, rid, userID); err != nil {
		return false, err
	}

	r.Hub.Publish("room_updated", map[string]any{
		"roomID": roomID,
		"event":  "member_left",
	}, nil)
	return true, nil
}

// RestartGame is the resolver for the restartGame field.
func (r *mutationResolver) RestartGame(ctx context.Context, roomID string) (*model.Room, error) {
	rid, err := strconv.ParseInt(roomID, 10, 64)
	if err != nil {
		return nil, err
	}

	room, err := r.RestartGameUseCase.Execute(ctx, rid)
	if err != nil {
		return nil, err
	}

	return mapRoomToGraphQL(room), nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context) (bool, error) {
	userID, err := auth.GetUserID(ctx)
	if err != nil {
		return false, fmt.Errorf("unauthorized: %w", err)
	}

	// UseCaseを実行
	if err := r.DeleteUserUseCase.Execute(ctx, userID); err != nil {
		return false, err
	}

	return true, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (*model.AuthPayload, error) {
	token, u, err := r.LoginUseCase.Execute(ctx, email, password)
	if err != nil {
		return nil, err
	}

	return &model.AuthPayload{
		Token: token,
		User: &model.User{
			ID:        strconv.FormatInt(u.ID, 10),
			Name:      u.Name,
			Email:     u.Email,
			CreatedAt: u.CreatedAt,
			UpdatedAt: u.UpdatedAt,
		},
	}, nil
}

// Hello is the resolver for the hello field.
func (r *queryResolver) Hello(ctx context.Context) (string, error) {
	r.Hub.Publish("Hello", map[string]any{"message": "Someone queried hello!"}, nil)
	return "hello", nil
}

// Rooms is the resolver for the rooms field.
// 部屋を取得する
func (r *queryResolver) Rooms(ctx context.Context) ([]*model.Room, error) {
	rooms, err := r.ListRoomsUseCase.Execute(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to list rooms: %w", err)
	}

	// GraphQLモデルに変換
	gqlRooms := make([]*model.Room, len(rooms))
	for i, room := range rooms {
		// メンバーIDの変換
		memberIDsStr := make([]string, len(room.MemberIDs))
		for j, mid := range room.MemberIDs {
			memberIDsStr[j] = strconv.FormatInt(mid, 10)
		}

		gqlRooms[i] = &model.Room{
			ID:        strconv.FormatInt(room.ID, 10),
			Name:      room.Name,
			OwnerID:   strconv.FormatInt(room.OwnerID, 10),
			MemberIDs: memberIDsStr,
			CreatedAt: room.CreatedAt,
			UpdatedAt: room.UpdatedAt,
		}
	}

	return gqlRooms, nil
}

// Room is the resolver for the room field.
func (r *queryResolver) Room(ctx context.Context, id string) (*model.Room, error) {
	rid, _ := strconv.ParseInt(id, 10, 64)

	room, err := r.GetRoomUseCase.Execute(ctx, rid)
	if err != nil {
		return nil, err
	}
	return mapRoomToGraphQL(room), nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	users, err := r.ListUsersUseCase.Execute(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to list users: %w", err)
	}

	var gqlUsers []*model.User
	for _, u := range users {
		gqlUsers = append(gqlUsers, &model.User{
			ID:        strconv.FormatInt(u.ID, 10),
			Name:      u.Name,
			Email:     u.Email,
			CreatedAt: u.CreatedAt,
			UpdatedAt: u.UpdatedAt,
		})
	}

	return gqlUsers, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	userID, err := strconv.ParseInt(id, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid user id: %w", err)
	}

	// DBから検索
	u, err := r.GetUserUseCase.Execute(ctx, userID)
	if err != nil {
		return nil, fmt.Errorf("user not found: %w", err)
	}

	// GraphQLの型に変換して返す
	return &model.User{
		ID:        strconv.FormatInt(u.ID, 10),
		Name:      u.Name,
		Email:     u.Email,
		CreatedAt: u.CreatedAt,
		UpdatedAt: u.UpdatedAt,
	}, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	currentUserID, err := auth.GetUserID(ctx)
	if err != nil {
		return nil, fmt.Errorf("unauthorized: %w", err)
	}

	// UseCaseを使って情報を取得
	u, err := r.GetUserUseCase.Execute(ctx, currentUserID)
	if err != nil {
		return nil, fmt.Errorf("failed to get current user: %w", err)
	}

	return &model.User{
		ID:        strconv.FormatInt(u.ID, 10),
		Name:      u.Name,
		Email:     u.Email,
		CreatedAt: u.CreatedAt,
		UpdatedAt: u.UpdatedAt,
	}, nil
}

// Owner is the resolver for the owner field.
func (r *roomResolver) Owner(ctx context.Context, obj *model.Room) (*model.User, error) {
	ownerID, err := strconv.ParseInt(obj.OwnerID, 10, 64)
	if err != nil {
		return nil, err
	}

	u, err := r.GetUserUseCase.Execute(ctx, ownerID)
	if err != nil {
		return nil, err
	}

	return &model.User{
		ID:        strconv.FormatInt(u.ID, 10),
		Name:      u.Name,
		Email:     u.Email,
		CreatedAt: u.CreatedAt,
		UpdatedAt: u.UpdatedAt,
	}, nil
}

// Members is the resolver for the members field.
func (r *roomResolver) Members(ctx context.Context, obj *model.Room) ([]*model.User, error) {
	var gqlUsers []*model.User

	// obj.MemberIDsを回してユーザー情報を取得
	for _, idStr := range obj.MemberIDs {
		mid, _ := strconv.ParseInt(idStr, 10, 64)

		u, err := r.GetUserUseCase.Execute(ctx, mid)
		if err == nil {
			gqlUsers = append(gqlUsers, &model.User{
				ID:        strconv.FormatInt(u.ID, 10),
				Name:      u.Name,
				Email:     u.Email,
				CreatedAt: u.CreatedAt,
				UpdatedAt: u.UpdatedAt,
			})
		}
	}

	return gqlUsers, nil
}

// Card returns CardResolver implementation.
func (r *Resolver) Card() CardResolver { return &cardResolver{r} }

// Game returns GameResolver implementation.
func (r *Resolver) Game() GameResolver { return &gameResolver{r} }

// GamePlayer returns GamePlayerResolver implementation.
func (r *Resolver) GamePlayer() GamePlayerResolver { return &gamePlayerResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Room returns RoomResolver implementation.
func (r *Resolver) Room() RoomResolver { return &roomResolver{r} }

type cardResolver struct{ *Resolver }
type gameResolver struct{ *Resolver }
type gamePlayerResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type roomResolver struct{ *Resolver }
