package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"errors"
	"fmt"
	"strconv"

	"github.com/ne241099/daifugo-server/graph/model"
)

// SignUp is the resolver for the signUp field.
func (r *mutationResolver) SignUp(ctx context.Context, in model.SignUpInput) (*model.User, error) {
	u, err := r.SignUpUseCase.Execute(ctx, in)
	if err != nil {
		return nil, errors.Join(err)
	}
	return &model.User{
		ID:        strconv.FormatInt(u.ID, 10),
		Email:     u.Email,
		Name:      u.Name,
		CreatedAt: u.CreatedAt,
		UpdatedAt: u.CreatedAt,
	}, nil
}

// CreateRoom is the resolver for the createRoom field.
// 部屋を作成する
func (r *mutationResolver) CreateRoom(ctx context.Context, name string) (*model.Room, error) {
	var ownerID int64 = 1

	// UseCaseを実行
	createdRoom, err := r.CreateRoomUseCase.Execute(ctx, name, ownerID)
	if err != nil {
		return nil, err
	}

	// ドメインモデル から GraphQLモデル への変換
	return &model.Room{
		ID:        strconv.FormatInt(createdRoom.ID, 10),
		Name:      createdRoom.Name,
		OwnerID:   strconv.FormatInt(createdRoom.OwnerID, 10),
		MemberIds: []string{strconv.FormatInt(createdRoom.OwnerID, 10)},
		CreatedAt: createdRoom.CreatedAt,
		UpdatedAt: createdRoom.UpdatedAt,
	}, nil
}

// JoinRoom is the resolver for the joinRoom field.
// 部屋に参加する
func (r *mutationResolver) JoinRoom(ctx context.Context, roomID string) (*model.Room, error) {
	rID, err := strconv.ParseInt(roomID, 10, 64)
	if err != nil {
		return nil, errors.Join(err)
	}

	var userID int64 = 2
	joinedRoom, err := r.JoinRoomUseCase.Execute(ctx, rID, userID)
	if err != nil {
		return nil, err
	}

	memberIdsStr := make([]string, len(joinedRoom.MemberIDs))
	for i, mid := range joinedRoom.MemberIDs {
		memberIdsStr[i] = strconv.FormatInt(mid, 10)
	}

	return &model.Room{
		ID:        strconv.FormatInt(joinedRoom.ID, 10),
		Name:      joinedRoom.Name,
		OwnerID:   strconv.FormatInt(joinedRoom.OwnerID, 10),
		MemberIds: memberIdsStr,
		CreatedAt: joinedRoom.CreatedAt,
		UpdatedAt: joinedRoom.UpdatedAt,
	}, nil
}

// Hello is the resolver for the hello field.
func (r *queryResolver) Hello(ctx context.Context) (string, error) {
	r.Hub.Publish("Hello", map[string]any{"message": "Someone queried hello!"}, nil)
	return "hello", nil
}

// Rooms is the resolver for the rooms field.
// 部屋を取得する
func (r *queryResolver) Rooms(ctx context.Context) ([]*model.Room, error) {
	return nil, fmt.Errorf("not implemented yet")
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
