package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"errors"
	"fmt"
	"strconv"

	"github.com/ne241099/daifugo-server/graph/model"
)

// SignUp is the resolver for the signUp field.
func (r *mutationResolver) SignUp(ctx context.Context, in model.SignUpInput) (*model.User, error) {
	u, err := r.SignUpUseCase.Execute(ctx, in)
	if err != nil {
		return nil, errors.Join(err)
	}
	return &model.User{
		ID:        strconv.FormatInt(u.ID, 10),
		Email:     u.Email,
		Name:      u.Name,
		CreatedAt: u.CreatedAt,
		UpdatedAt: u.CreatedAt,
	}, nil
}

// CreateRoom is the resolver for the createRoom field.
// 部屋を作成する
func (r *mutationResolver) CreateRoom(ctx context.Context, name string) (*model.Room, error) {
	var ownerID int64 = 1

	// UseCaseを実行
	createdRoom, err := r.CreateRoomUseCase.Execute(ctx, name, ownerID)
	if err != nil {
		return nil, err
	}

	// ドメインモデル から GraphQLモデル への変換
	gqlRoom := &model.Room{
		ID:        strconv.FormatInt(createdRoom.ID, 10),
		Name:      createdRoom.Name,
		OwnerID:   strconv.FormatInt(createdRoom.OwnerID, 10),
		MemberIds: []string{strconv.FormatInt(createdRoom.OwnerID, 10)},
		CreatedAt: createdRoom.CreatedAt,
		UpdatedAt: createdRoom.UpdatedAt,
	}

	r.Hub.Publish("room_created", gqlRoom, nil)
	return gqlRoom, nil
}

// JoinRoom is the resolver for the joinRoom field.
// 部屋に参加する
func (r *mutationResolver) JoinRoom(ctx context.Context, roomID string) (*model.Room, error) {
	rID, err := strconv.ParseInt(roomID, 10, 64)
	if err != nil {
		return nil, errors.Join(err)
	}

	var userID int64 = 2
	joinedRoom, err := r.JoinRoomUseCase.Execute(ctx, rID, userID)
	if err != nil {
		return nil, err
	}

	memberIdsStr := make([]string, len(joinedRoom.MemberIDs))
	for i, mid := range joinedRoom.MemberIDs {
		memberIdsStr[i] = strconv.FormatInt(mid, 10)
	}

	gqlRoom := &model.Room{
		ID:        strconv.FormatInt(joinedRoom.ID, 10),
		Name:      joinedRoom.Name,
		OwnerID:   strconv.FormatInt(joinedRoom.OwnerID, 10),
		MemberIds: memberIdsStr,
		CreatedAt: joinedRoom.CreatedAt,
		UpdatedAt: joinedRoom.UpdatedAt,
	}

	r.Hub.Publish("room_updated", gqlRoom, nil)
	return gqlRoom, nil
}

// Hello is the resolver for the hello field.
func (r *queryResolver) Hello(ctx context.Context) (string, error) {
	r.Hub.Publish("Hello", map[string]any{"message": "Someone queried hello!"}, nil)
	return "hello", nil
}

// Rooms is the resolver for the rooms field.
// 部屋を取得する
func (r *queryResolver) Rooms(ctx context.Context) ([]*model.Room, error) {
	rooms, err := r.ListRoomsUseCase.Execute(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to list rooms: %w", err)
	}

	// GraphQLモデルに変換
	gqlRooms := make([]*model.Room, len(rooms))
	for i, room := range rooms {
		// メンバーIDの変換
		memberIdsStr := make([]string, len(room.MemberIDs))
		for j, mid := range room.MemberIDs {
			memberIdsStr[j] = strconv.FormatInt(mid, 10)
		}

		gqlRooms[i] = &model.Room{
			ID:        strconv.FormatInt(room.ID, 10),
			Name:      room.Name,
			OwnerID:   strconv.FormatInt(room.OwnerID, 10),
			MemberIds: memberIdsStr,
			CreatedAt: room.CreatedAt,
			UpdatedAt: room.UpdatedAt,
		}
	}

	return gqlRooms, nil
}

// Owner is the resolver for the owner field.
func (r *roomResolver) Owner(ctx context.Context, obj *model.Room) (*model.User, error) {
	ownerID, err := strconv.ParseInt(obj.OwnerID, 10, 64)
	if err != nil {
		return nil, err
	}

	u, err := r.GetUserUseCase.Execute(ctx, ownerID)
	if err != nil {
		return nil, err
	}

	return &model.User{
		ID:        strconv.FormatInt(u.ID, 10),
		Name:      u.Name,
		Email:     u.Email,
		CreatedAt: u.CreatedAt,
		UpdatedAt: u.UpdatedAt,
	}, nil
}

// Members is the resolver for the members field.
func (r *roomResolver) Members(ctx context.Context, obj *model.Room) ([]*model.User, error) {
	var gqlUsers []*model.User

	// obj.MemberIdsを回してユーザー情報を取得
	for _, idStr := range obj.MemberIds {
		mid, _ := strconv.ParseInt(idStr, 10, 64)

		u, err := r.GetUserUseCase.Execute(ctx, mid)
		if err == nil {
			gqlUsers = append(gqlUsers, &model.User{
				ID:        strconv.FormatInt(u.ID, 10),
				Name:      u.Name,
				Email:     u.Email,
				CreatedAt: u.CreatedAt,
				UpdatedAt: u.UpdatedAt,
			})
		}
	}

	return gqlUsers, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Room returns RoomResolver implementation.
func (r *Resolver) Room() RoomResolver { return &roomResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type roomResolver struct{ *Resolver }
