// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Card struct {
	ID   int32  `json:"id"`
	Suit string `json:"suit"`
	Rank int32  `json:"rank"`
}

type Game struct {
	Players      []*GamePlayer `json:"players"`
	TurnUserID   string        `json:"turnUserId"`
	FieldCards   []*Card       `json:"fieldCards"`
	IsRevolution bool          `json:"isRevolution"`
}

type GamePlayer struct {
	UserID string  `json:"userId"`
	User   *User   `json:"user"`
	Hand   []*Card `json:"hand"`
	Rank   int32   `json:"rank"`
}

type Mutation struct {
}

type Query struct {
}

type Room struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	OwnerID   string    `json:"ownerId"`
	MemberIds []string  `json:"memberIds"`
	Owner     *User     `json:"owner"`
	Members   []*User   `json:"members"`
	Game      *Game     `json:"game,omitempty"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type User struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type SignUpInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}
